import React, { useState } from 'react';
import { Box, Button, Menu, MenuItem, ListItemIcon, ListItemText, Divider, Snackbar, Alert } from '@mui/material';
import FileDownloadOutlinedIcon from '@mui/icons-material/FileDownloadOutlined';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import ArticleOutlinedIcon from '@mui/icons-material/ArticleOutlined';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

function summaryToMarkdown(summary) {
    const lines = ['# Meeting Summary', ''];

    if (summary?.topics?.length) {
        lines.push('## 📌 Main Topics', '');
        summary.topics.forEach((t) => lines.push(`- ${t}`));
        lines.push('');
    }

    if (summary?.decisions?.length) {
        lines.push('## 💡 Key Decisions', '');
        summary.decisions.forEach((d) => lines.push(`- ${d}`));
        lines.push('');
    }

    if (summary?.action_items?.length) {
        lines.push('## ✅ Action Items', '');
        summary.action_items.forEach((item) => {
            if (typeof item === 'object') {
                lines.push(`- **${item.task}** — ${item.owner || 'Unassigned'} *(${item.deadline || 'No deadline'})*`);
            } else {
                lines.push(`- ${item}`);
            }
        });
        lines.push('');
    }

    lines.push(`---`, `*Generated by MeetingMind AI · ${new Date().toLocaleString()}*`);
    return lines.join('\n');
}

function ExportMenu({ summary }) {
    const [anchor, setAnchor] = useState(null);
    const [toast, setToast] = useState({ open: false, msg: '', severity: 'success' });

    const open = Boolean(anchor);

    const handleOpen = (e) => setAnchor(e.currentTarget);
    const handleClose = () => setAnchor(null);

    const showToast = (msg, severity = 'success') => {
        setToast({ open: true, msg, severity });
    };

    const copyMarkdown = async () => {
        const md = summaryToMarkdown(summary);
        try {
            await navigator.clipboard.writeText(md);
            showToast('Copied as Markdown ✓');
        } catch {
            showToast('Copy failed — try again', 'error');
        }
        handleClose();
    };

    const downloadTxt = () => {
        const md = summaryToMarkdown(summary);
        const blob = new Blob([md], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `meeting-summary-${new Date().toISOString().slice(0, 10)}.txt`;
        a.click();
        URL.revokeObjectURL(url);
        showToast('Downloaded as .txt ✓');
        handleClose();
    };

    const downloadJson = () => {
        const blob = new Blob([JSON.stringify(summary, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `meeting-summary-${new Date().toISOString().slice(0, 10)}.json`;
        a.click();
        URL.revokeObjectURL(url);
        showToast('Downloaded as JSON ✓');
        handleClose();
    };

    return (
        <>
            <Button
                size="small"
                onClick={handleOpen}
                endIcon={<ExpandMoreIcon sx={{ fontSize: '14px !important', transform: open ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s' }} />}
                startIcon={<FileDownloadOutlinedIcon sx={{ fontSize: '16px !important' }} />}
                sx={{
                    fontSize: '0.78rem',
                    fontWeight: 600,
                    color: '#94a3b8',
                    background: 'rgba(255,255,255,0.04)',
                    border: '1px solid rgba(255,255,255,0.1)',
                    borderRadius: '9px',
                    px: 1.8,
                    py: 0.7,
                    '&:hover': {
                        background: 'rgba(255,255,255,0.08)',
                        color: '#f1f5f9',
                        borderColor: 'rgba(255,255,255,0.2)',
                    },
                    transition: 'all 0.2s',
                }}
            >
                Export
            </Button>

            <Menu
                anchorEl={anchor}
                open={open}
                onClose={handleClose}
                transformOrigin={{ horizontal: 'right', vertical: 'top' }}
                anchorOrigin={{ horizontal: 'right', vertical: 'bottom' }}
                PaperProps={{
                    sx: {
                        background: '#111827',
                        border: '1px solid rgba(255,255,255,0.09)',
                        borderRadius: '12px',
                        boxShadow: '0 16px 48px rgba(0,0,0,0.5)',
                        minWidth: 200,
                        mt: 0.5,
                        '& .MuiMenuItem-root': {
                            fontSize: '0.82rem',
                            color: '#94a3b8',
                            borderRadius: '7px',
                            mx: 0.5,
                            px: 1.5,
                            py: 1,
                            '&:hover': { background: 'rgba(99,102,241,0.1)', color: '#e2e8f0' },
                        },
                    },
                }}
            >
                <Box sx={{ px: 2, pt: 1.2, pb: 0.5 }}>
                    <Box component="span" sx={{ fontSize: '0.65rem', color: '#475569', fontWeight: 600, letterSpacing: '0.8px', textTransform: 'uppercase' }}>
                        Export summary
                    </Box>
                </Box>
                <Divider sx={{ borderColor: 'rgba(255,255,255,0.06)', my: 0.5 }} />

                <MenuItem onClick={copyMarkdown}>
                    <ListItemIcon sx={{ minWidth: 30 }}>
                        <ContentCopyIcon sx={{ fontSize: 15, color: '#6366f1' }} />
                    </ListItemIcon>
                    <ListItemText primary="Copy as Markdown" primaryTypographyProps={{ fontSize: '0.82rem' }} />
                </MenuItem>

                <MenuItem onClick={downloadTxt}>
                    <ListItemIcon sx={{ minWidth: 30 }}>
                        <ArticleOutlinedIcon sx={{ fontSize: 15, color: '#10b981' }} />
                    </ListItemIcon>
                    <ListItemText primary="Download .txt" primaryTypographyProps={{ fontSize: '0.82rem' }} />
                </MenuItem>

                <MenuItem onClick={downloadJson}>
                    <ListItemIcon sx={{ minWidth: 30 }}>
                        <FileDownloadOutlinedIcon sx={{ fontSize: 15, color: '#f59e0b' }} />
                    </ListItemIcon>
                    <ListItemText primary="Download .json" primaryTypographyProps={{ fontSize: '0.82rem' }} />
                </MenuItem>
            </Menu>

            <Snackbar
                open={toast.open}
                autoHideDuration={2500}
                onClose={() => setToast((p) => ({ ...p, open: false }))}
                anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
            >
                <Alert
                    severity={toast.severity}
                    sx={{
                        background: toast.severity === 'success' ? 'rgba(16,185,129,0.15)' : 'rgba(244,63,94,0.15)',
                        border: `1px solid ${toast.severity === 'success' ? 'rgba(16,185,129,0.3)' : 'rgba(244,63,94,0.3)'}`,
                        color: toast.severity === 'success' ? '#10b981' : '#f43f5e',
                        fontWeight: 600,
                        fontSize: '0.8rem',
                        borderRadius: '10px',
                    }}
                >
                    {toast.msg}
                </Alert>
            </Snackbar>
        </>
    );
}

export default ExportMenu;
